NAME: 'AlexNet_C42_OTB'
TRACKER_TYPE: 'spm_tracker'

USE_PIL_LIB: False

MODEL:
  BACKBONE: 'alexnet'
  FEAT_NAME: 'conv5'
  ANCHOR_RATIOS: [0.33, 0.5, 1.0, 2.0, 3.0]
  ANCHOR_SCALES: [8.0]
  Z_CONTEXT_AMOUNT: 0.5
  
  CM_CLS_SCALE_FACTOR: 0.001
  CM_BBOX_SCALE_FACTOR: 0.001
  CM_WEIGHTS_FILE: 'data/models/spm_tracker/AlexNet_C42_OTB/cm_stage.pt'

  FM_FEAT_NAME_LIST: ['conv4', 'conv2']
  FM_ROI_FEAT_BN: True
  FM_ROI_POOL_SIZE: [6, 6]
  FM_POOL_CONVS: [256]
  FM_HIDDEN_LAYER_CHANNEL: 256
  FM_NUM_LINEAR_LAYERS: 2
  FM_BBOX_VAR_INV: [5.0, 5.0, 10.0, 10.0]
  FM_WEIGHTS_FILE: 'data/models/spm_tracker/AlexNet_C42_OTB/fm_stage.pt'

INFERENCE:
  DEBUG_VIS_ON: False
  Z_SIZE: 127
  X_SIZE: 271
  FM_SCORE_INFLUENCE: 0.5
  FM_BBOX_INFLUENCE: 3.0
  WINDOWS_INFLUENCE: 0.5
  LR: 0.5
  MAX_SCORE_THRESHOLD: 0.2
  SCORE_THRESH_FACTOR: 0.1
  NUM_CANDIDATES: 9
  NUM_NEAR_CANDIDATES: 1
  NMS_THRESHOLD: 0.5
